[workspace]
members = [
    "lib",
    "app",
    "cli",
    "sandbox",
    "tools",
    "controller",
    "crds",
    "cfgstore",
]
resolver = "2"
[workspace.package]
version = "0.0.11-alpha.5"
authors = ["Sébastien Huss <sebastien.huss@gmail.com>"]
edition = "2024"
license = "BSD-3-Clause"

[workspace.lints.rust]
unsafe_code = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
unreachable = "deny"
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"
print_stdout = "deny"
print_stderr = "deny"
arithmetic_side_effects = "deny"
multiple_crate_versions = "allow"
