apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanyline
  namespace: media-station
  labels:
    app: vanyline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanyline
  template:
    metadata:
      labels:
        app: vanyline
    spec:
      containers:
      - name: vanyline
        image: docker.io/sebt3/vanyline-app:0.0.1-alpha.1
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: vanyline-config
        env:
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: vanyline-secrets
              key: COOKIE_SECRET
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: vanyline-secrets
              key: DATABASE_URL
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: vanyline-openid
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: vanyline-openid
              key: OIDC_CLIENT_SECRET
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 512Mi
