[package]
name = "vanyline-tools"
version = "0.0.1-alpha.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full", "process"] }
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
futures = "0.3"
regex = "1"
globset = "0.4"
ignore = "0.4"
libc = "0.2"

[dev-dependencies]
tempfile = "3"
